# Generated by Django 4.1.6 on 2023-02-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Empresa')),
                ('name', models.CharField(max_length=50, verbose_name='Representante')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('buy_price', models.FloatField(default=0.0, verbose_name='Precio de Compra')),
                ('sell_price', models.FloatField(default=0.0, verbose_name='Precio de Venta')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
